project:
  type: website

website:
  title: "Reproducible RNA-Seq Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Analysis Report

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: true
    code-tools: true
    smooth-scroll: true
    theme: cosmo
    css: styles.css

execute:
  echo: false
  warning: false
  message: false
